# Generated by Django 4.1.7 on 2023-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
