# Generated by Django 4.1.7 on 2023-03-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='prod_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
