# Generated by Django 4.1.7 on 2023-03-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptionplan_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
